### THRIFT ### 
# World Values Survey (WVS) and European Values Survey (EVS)
# Compute the fraction of participants in each country that considers thrift to be important and average this value over all existing waves

which.countries <- WVSfinal %>% select(IOC) %>% distinct()
which.countries.2 <- EVSfinal %>% select(IOC) %>% distinct()

EVS.ALB <- EVSfinal %>% filter(IOC=="ALB") %>% filter(syear < 2010) %>% na.omit()
WVS.ALB <- WVSfinal %>% filter(IOC=="ALB") %>% filter(syear < 2010) %>% na.omit()
ALB <- rbind(EVS.ALB, WVS.ALB) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ALG <- EVSfinal %>% filter(IOC=="ALG") %>% filter(syear < 2010) %>% na.omit()
WVS.ALG <- WVSfinal %>% filter(IOC=="ALG") %>% filter(syear < 2010) %>% na.omit()
ALG <- rbind(EVS.ALG, WVS.ALG) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.AZE <- EVSfinal %>% filter(IOC=="AZE") %>% filter(syear < 2010) %>% na.omit()
WVS.AZE <- WVSfinal %>% filter(IOC=="AZE") %>% filter(syear < 2010) %>% na.omit()
AZE <- rbind(EVS.AZE, WVS.AZE) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ARG <- EVSfinal %>% filter(IOC=="ARG") %>% filter(syear < 2010) %>% na.omit()
WVS.ARG <- WVSfinal %>% filter(IOC=="ARG") %>% filter(syear < 2010) %>% na.omit()
ARG <- rbind(EVS.ARG, WVS.ARG) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.AUS <- EVSfinal %>% filter(IOC=="AUS") %>% filter(syear < 2010) %>% na.omit()
WVS.AUS <- WVSfinal %>% filter(IOC=="AUS") %>% filter(syear < 2010) %>% na.omit()
AUS <- rbind(EVS.AUS, WVS.AUS) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.BAN <- EVSfinal %>% filter(IOC=="BAN") %>% filter(syear < 2010) %>% na.omit()
WVS.BAN <- WVSfinal %>% filter(IOC=="BAN") %>% filter(syear < 2010) %>% na.omit()
BAN <- rbind(EVS.BAN, WVS.BAN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ARM <- EVSfinal %>% filter(IOC=="ARM") %>% filter(syear < 2010) %>% na.omit()
WVS.ARM <- WVSfinal %>% filter(IOC=="ARM") %>% filter(syear < 2010) %>% na.omit()
ARM <- rbind(EVS.ARM, WVS.ARM) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.BRA <- EVSfinal %>% filter(IOC=="BRA") %>% filter(syear < 2010) %>% na.omit()
WVS.BRA <- WVSfinal %>% filter(IOC=="BRA") %>% filter(syear < 2010) %>% na.omit()
BRA <- rbind(EVS.BRA, WVS.BRA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.BUL <- EVSfinal %>% filter(IOC=="BUL") %>% filter(syear < 2010) %>% na.omit()
WVS.BUL <- WVSfinal %>% filter(IOC=="BUL") %>% filter(syear < 2010) %>% na.omit()
BUL <- rbind(EVS.BUL, WVS.BUL) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.BLR <- EVSfinal %>% filter(IOC=="BLR") %>% filter(syear < 2010) %>% na.omit()
WVS.BLR <- WVSfinal %>% filter(IOC=="BLR") %>% filter(syear < 2010) %>% na.omit()
BLR <- rbind(EVS.BLR, WVS.BLR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.CAN <- EVSfinal %>% filter(IOC=="CAN") %>% filter(syear < 2010) %>% na.omit()
WVS.CAN <- WVSfinal %>% filter(IOC=="CAN") %>% filter(syear < 2010) %>% na.omit()
CAN <- rbind(EVS.CAN, WVS.CAN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.CHI <- EVSfinal %>% filter(IOC=="CHI") %>% filter(syear < 2010) %>% na.omit()
WVS.CHI <- WVSfinal %>% filter(IOC=="CHI") %>% filter(syear < 2010) %>% na.omit()
CHI <- rbind(EVS.CHI, WVS.CHI) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.COL <- EVSfinal %>% filter(IOC=="COL") %>% filter(syear < 2010) %>% na.omit()
WVS.COL <- WVSfinal %>% filter(IOC=="COL") %>% filter(syear < 2010) %>% na.omit()
COL <- rbind(EVS.COL, WVS.COL) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.CRO <- EVSfinal %>% filter(IOC=="CRO") %>% filter(syear < 2010) %>% na.omit()
WVS.CRO <- WVSfinal %>% filter(IOC=="CRO") %>% filter(syear < 2010) %>% na.omit()
CRO <- rbind(EVS.CRO, WVS.CRO) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ESA <- EVSfinal %>% filter(IOC=="ESA") %>% filter(syear < 2010) %>% na.omit()
WVS.ESA <- WVSfinal %>% filter(IOC=="ESA") %>% filter(syear < 2010) %>% na.omit()
ESA <- rbind(EVS.ESA, WVS.ESA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.EST <- EVSfinal %>% filter(IOC=="EST") %>% filter(syear < 2010) %>% na.omit()
WVS.EST <- WVSfinal %>% filter(IOC=="EST") %>% filter(syear < 2010) %>% na.omit()
EST <- rbind(EVS.EST, WVS.EST) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.FIN <- EVSfinal %>% filter(IOC=="FIN") %>% filter(syear < 2010) %>% na.omit()
WVS.FIN <- WVSfinal %>% filter(IOC=="FIN") %>% filter(syear < 2010) %>% na.omit()
FIN <- rbind(EVS.FIN, WVS.FIN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.FRA <- EVSfinal %>% filter(IOC=="FRA") %>% filter(syear < 2010) %>% na.omit()
WVS.FRA <- WVSfinal %>% filter(IOC=="FRA") %>% filter(syear < 2010) %>% na.omit()
FRA <- rbind(EVS.FRA, WVS.FRA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.GEO <- EVSfinal %>% filter(IOC=="GEO") %>% filter(syear < 2010) %>% na.omit()
WVS.GEO <- WVSfinal %>% filter(IOC=="GEO") %>% filter(syear < 2010) %>% na.omit()
GEO <- rbind(EVS.GEO, WVS.GEO) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.HUN <- EVSfinal %>% filter(IOC=="HUN") %>% filter(syear < 2010) %>% na.omit()
WVS.HUN <- WVSfinal %>% filter(IOC=="HUN") %>% filter(syear < 2010) %>% na.omit()
HUN <- rbind(EVS.HUN, WVS.HUN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.IND <- EVSfinal %>% filter(IOC=="IND") %>% filter(syear < 2010) %>% na.omit()
WVS.IND <- WVSfinal %>% filter(IOC=="IND") %>% filter(syear < 2010) %>% na.omit()
IND <- rbind(EVS.IND, WVS.IND) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.INA <- EVSfinal %>% filter(IOC=="INA") %>% filter(syear < 2010) %>% na.omit()
WVS.INA <- WVSfinal %>% filter(IOC=="INA") %>% filter(syear < 2010) %>% na.omit()
INA <- rbind(EVS.INA, WVS.INA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.IRI <- EVSfinal %>% filter(IOC=="IRI") %>% filter(syear < 2010) %>% na.omit()
WVS.IRI <- WVSfinal %>% filter(IOC=="IRI") %>% filter(syear < 2010) %>% na.omit()
IRI <- rbind(EVS.IRI, WVS.IRI) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.IRQ <- EVSfinal %>% filter(IOC=="IRQ") %>% filter(syear < 2010) %>% na.omit()
WVS.IRQ <- WVSfinal %>% filter(IOC=="IRQ") %>% filter(syear < 2010) %>% na.omit()
IRQ <- rbind(EVS.IRQ, WVS.IRQ) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ISR <- EVSfinal %>% filter(IOC=="ISR") %>% filter(syear < 2010) %>% na.omit()
WVS.ISR <- WVSfinal %>% filter(IOC=="ISR") %>% filter(syear < 2010) %>% na.omit()
ISR <- rbind(EVS.ISR, WVS.ISR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ITA <- EVSfinal %>% filter(IOC=="ITA") %>% filter(syear < 2010) %>% na.omit()
WVS.ITA <- WVSfinal %>% filter(IOC=="ITA") %>% filter(syear < 2010) %>% na.omit()
ITA <- rbind(EVS.ITA, WVS.ITA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.JPN <- EVSfinal %>% filter(IOC=="JPN") %>% filter(syear < 2010) %>% na.omit()
WVS.JPN <- WVSfinal %>% filter(IOC=="JPN") %>% filter(syear < 2010) %>% na.omit()
JPN <- rbind(EVS.JPN, WVS.JPN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.KSA <- EVSfinal %>% filter(IOC=="KSA") %>% filter(syear < 2010) %>% na.omit()
WVS.KSA <- WVSfinal %>% filter(IOC=="KSA") %>% filter(syear < 2010) %>% na.omit()
KSA <- rbind(EVS.KSA, WVS.KSA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.JOR <- EVSfinal %>% filter(IOC=="JOR") %>% filter(syear < 2010) %>% na.omit()
WVS.JOR <- WVSfinal %>% filter(IOC=="JOR") %>% filter(syear < 2010) %>% na.omit()
JOR <- rbind(EVS.JOR, WVS.JOR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.KGZ <- EVSfinal %>% filter(IOC=="KGZ") %>% filter(syear < 2010) %>% na.omit()
WVS.KGZ <- WVSfinal %>% filter(IOC=="KGZ") %>% filter(syear < 2010) %>% na.omit()
KGZ <- rbind(EVS.KGZ, WVS.KGZ) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.LAT <- EVSfinal %>% filter(IOC=="LAT") %>% filter(syear < 2010) %>% na.omit()
WVS.LAT <- WVSfinal %>% filter(IOC=="LAT") %>% filter(syear < 2010) %>% na.omit()
LAT <- rbind(EVS.LAT, WVS.LAT) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.LTU <- EVSfinal %>% filter(IOC=="LTU") %>% filter(syear < 2010) %>% na.omit()
WVS.LTU <- WVSfinal %>% filter(IOC=="LTU") %>% filter(syear < 2010) %>% na.omit()
LTU <- rbind(EVS.LTU, WVS.LTU) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.MEX <- EVSfinal %>% filter(IOC=="MEX") %>% filter(syear < 2010) %>% na.omit()
WVS.MEX <- WVSfinal %>% filter(IOC=="MEX") %>% filter(syear < 2010) %>% na.omit()
MEX <- rbind(EVS.MEX, WVS.MEX) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.MKD <- EVSfinal %>% filter(IOC=="MKD") %>% filter(syear < 2010) %>% na.omit()
WVS.MKD <- WVSfinal %>% filter(IOC=="MKD") %>% filter(syear < 2010) %>% na.omit()
MKD <- rbind(EVS.MKD, WVS.MKD) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.MDA <- EVSfinal %>% filter(IOC=="MDA") %>% filter(syear < 2010) %>% na.omit()
WVS.MDA <- WVSfinal %>% filter(IOC=="MDA") %>% filter(syear < 2010) %>% na.omit()
MDA <- rbind(EVS.MDA, WVS.MDA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.MAR <- EVSfinal %>% filter(IOC=="MAR") %>% filter(syear < 2010) %>% na.omit()
WVS.MAR <- WVSfinal %>% filter(IOC=="MAR") %>% filter(syear < 2010) %>% na.omit()
MAR <- rbind(EVS.MAR, WVS.MAR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.NED <- EVSfinal %>% filter(IOC=="NED") %>% filter(syear < 2010) %>% na.omit()
WVS.NED <- WVSfinal %>% filter(IOC=="NED") %>% filter(syear < 2010) %>% na.omit()
NED <- rbind(EVS.NED, WVS.NED) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.NZL <- EVSfinal %>% filter(IOC=="NZL") %>% filter(syear < 2010) %>% na.omit()
WVS.NZL <- WVSfinal %>% filter(IOC=="NZL") %>% filter(syear < 2010) %>% na.omit()
NZL <- rbind(EVS.NZL, WVS.NZL) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.NGR <- EVSfinal %>% filter(IOC=="NGR") %>% filter(syear < 2010) %>% na.omit()
WVS.NGR <- WVSfinal %>% filter(IOC=="NGR") %>% filter(syear < 2010) %>% na.omit()
NGR <- rbind(EVS.NGR, WVS.NGR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.NOR <- EVSfinal %>% filter(IOC=="NOR") %>% filter(syear < 2010) %>% na.omit()
WVS.NOR <- WVSfinal %>% filter(IOC=="NOR") %>% filter(syear < 2010) %>% na.omit()
NOR <- rbind(EVS.NOR, WVS.NOR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.PAK <- EVSfinal %>% filter(IOC=="PAK") %>% filter(syear < 2010) %>% na.omit()
WVS.PAK <- WVSfinal %>% filter(IOC=="PAK") %>% filter(syear < 2010) %>% na.omit()
PAK <- rbind(EVS.PAK, WVS.PAK) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.PER <- EVSfinal %>% filter(IOC=="PER") %>% filter(syear < 2010) %>% na.omit()
WVS.PER <- WVSfinal %>% filter(IOC=="PER") %>% filter(syear < 2010) %>% na.omit()
PER <- rbind(EVS.PER, WVS.PER) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.PHI <- EVSfinal %>% filter(IOC=="PHI") %>% filter(syear < 2010) %>% na.omit()
WVS.PHI <- WVSfinal %>% filter(IOC=="PHI") %>% filter(syear < 2010) %>% na.omit()
PHI <- rbind(EVS.PHI, WVS.PHI) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.POL <- EVSfinal %>% filter(IOC=="POL") %>% filter(syear < 2010) %>% na.omit()
WVS.POL <- WVSfinal %>% filter(IOC=="POL") %>% filter(syear < 2010) %>% na.omit()
POL <- rbind(EVS.POL, WVS.POL) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.PUR <- EVSfinal %>% filter(IOC=="PUR") %>% filter(syear < 2010) %>% na.omit()
WVS.PUR <- WVSfinal %>% filter(IOC=="PUR") %>% filter(syear < 2010) %>% na.omit()
PUR <- rbind(EVS.PUR, WVS.PUR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ROU <- EVSfinal %>% filter(IOC=="ROU") %>% filter(syear < 2010) %>% na.omit()
WVS.ROU <- WVSfinal %>% filter(IOC=="ROU") %>% filter(syear < 2010) %>% na.omit()
ROU <- rbind(EVS.ROU, WVS.ROU) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.RUS <- EVSfinal %>% filter(IOC=="RUS") %>% filter(syear < 2010) %>% na.omit()
WVS.RUS <- WVSfinal %>% filter(IOC=="RUS") %>% filter(syear < 2010) %>% na.omit()
RUS <- rbind(EVS.RUS, WVS.RUS) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.SGP <- EVSfinal %>% filter(IOC=="SGP") %>% filter(syear < 2010) %>% na.omit()
WVS.SGP <- WVSfinal %>% filter(IOC=="SGP") %>% filter(syear < 2010) %>% na.omit()
SGP <- rbind(EVS.SGP, WVS.SGP) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.SVK <- EVSfinal %>% filter(IOC=="SVK") %>% filter(syear < 2010) %>% na.omit()
WVS.SVK <- WVSfinal %>% filter(IOC=="SVK") %>% filter(syear < 2010) %>% na.omit()
SVK <- rbind(EVS.SVK, WVS.SVK) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.SLO <- EVSfinal %>% filter(IOC=="SLO") %>% filter(syear < 2010) %>% na.omit()
WVS.SLO <- WVSfinal %>% filter(IOC=="SLO") %>% filter(syear < 2010) %>% na.omit()
SLO <- rbind(EVS.SLO, WVS.SLO) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.RSA <- EVSfinal %>% filter(IOC=="RSA") %>% filter(syear < 2010) %>% na.omit()
WVS.RSA <- WVSfinal %>% filter(IOC=="RSA") %>% filter(syear < 2010) %>% na.omit()
RSA <- rbind(EVS.RSA, WVS.RSA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ZIM <- EVSfinal %>% filter(IOC=="ZIM") %>% filter(syear < 2010) %>% na.omit()
WVS.ZIM <- WVSfinal %>% filter(IOC=="ZIM") %>% filter(syear < 2010) %>% na.omit()
ZIM <- rbind(EVS.ZIM, WVS.ZIM) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.ESP <- EVSfinal %>% filter(IOC=="ESP") %>% filter(syear < 2010) %>% na.omit()
WVS.ESP <- WVSfinal %>% filter(IOC=="ESP") %>% filter(syear < 2010) %>% na.omit()
ESP <- rbind(EVS.ESP, WVS.ESP) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.SWE <- EVSfinal %>% filter(IOC=="SWE") %>% filter(syear < 2010) %>% na.omit()
WVS.SWE <- WVSfinal %>% filter(IOC=="SWE") %>% filter(syear < 2010) %>% na.omit()
SWE <- rbind(EVS.SWE, WVS.SWE) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.SUI <- EVSfinal %>% filter(IOC=="SUI") %>% filter(syear < 2010) %>% na.omit()
WVS.SUI <- WVSfinal %>% filter(IOC=="SUI") %>% filter(syear < 2010) %>% na.omit()
SUI <- rbind(EVS.SUI, WVS.SUI) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.TUR <- EVSfinal %>% filter(IOC=="TUR") %>% filter(syear < 2010) %>% na.omit()
WVS.TUR <- WVSfinal %>% filter(IOC=="TUR") %>% filter(syear < 2010) %>% na.omit()
TUR <- rbind(EVS.TUR, WVS.TUR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.UGA <- EVSfinal %>% filter(IOC=="UGA") %>% filter(syear < 2010) %>% na.omit()
WVS.UGA <- WVSfinal %>% filter(IOC=="UGA") %>% filter(syear < 2010) %>% na.omit()
UGA <- rbind(EVS.UGA, WVS.UGA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.UKR <- EVSfinal %>% filter(IOC=="UKR") %>% filter(syear < 2010) %>% na.omit()
WVS.UKR <- WVSfinal %>% filter(IOC=="UKR") %>% filter(syear < 2010) %>% na.omit()
UKR <- rbind(EVS.UKR, WVS.UKR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.EGY <- EVSfinal %>% filter(IOC=="EGY") %>% filter(syear < 2010) %>% na.omit()
WVS.EGY <- WVSfinal %>% filter(IOC=="EGY") %>% filter(syear < 2010) %>% na.omit()
EGY <- rbind(EVS.EGY, WVS.EGY) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.TAN <- EVSfinal %>% filter(IOC=="TAN") %>% filter(syear < 2010) %>% na.omit()
WVS.TAN <- WVSfinal %>% filter(IOC=="TAN") %>% filter(syear < 2010) %>% na.omit()
TAN <- rbind(EVS.TAN, WVS.TAN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.USA <- EVSfinal %>% filter(IOC=="USA") %>% filter(syear < 2010) %>% na.omit()
WVS.USA <- WVSfinal %>% filter(IOC=="USA") %>% filter(syear < 2010) %>% na.omit()
USA <- rbind(EVS.USA, WVS.USA) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.URU <- EVSfinal %>% filter(IOC=="URU") %>% filter(syear < 2010) %>% na.omit()
WVS.URU <- WVSfinal %>% filter(IOC=="URU") %>% filter(syear < 2010) %>% na.omit()
URU <- rbind(EVS.URU, WVS.URU) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.VEN <- EVSfinal %>% filter(IOC=="VEN") %>% filter(syear < 2010) %>% na.omit()
WVS.VEN <- WVSfinal %>% filter(IOC=="VEN") %>% filter(syear < 2010) %>% na.omit()
VEN <- rbind(EVS.VEN, WVS.VEN) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.GER <- EVSfinal %>% filter(IOC=="GER") %>% filter(syear < 2010) %>% na.omit()
WVS.GER <- WVSfinal %>% filter(IOC=="GER") %>% filter(syear < 2010) %>% na.omit()
GER <- rbind(EVS.GER, WVS.GER) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.CZE <- EVSfinal %>% filter(IOC=="CZE") %>% filter(syear < 2010) %>% na.omit()
WVS.CZE <- WVSfinal %>% filter(IOC=="CZE") %>% filter(syear < 2010) %>% na.omit()
CZE <- rbind(EVS.CZE, WVS.CZE) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()
EVS.GBR <- EVSfinal %>% filter(IOC=="GBR") %>% filter(syear < 2010) %>% na.omit()
WVS.GBR <- WVSfinal %>% filter(IOC=="GBR") %>% filter(syear < 2010) %>% na.omit()
GBR <- rbind(EVS.GBR, WVS.GBR) %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) %>% distinct()



rm(EVS.ALB, WVS.ALB, EVS.ALG, WVS.ALG, EVS.AZE, WVS.AZE, EVS.ARG, WVS.ARG, EVS.AUS, WVS.AUS, EVS.BAN, WVS.BAN, EVS.ARM, WVS.ARM, EVS.BRA, WVS.BRA, EVS.BUL,
   WVS.BUL, EVS.BLR, WVS.BLR, EVS.CAN, WVS.CAN, EVS.VEN, WVS.VEN, EVS.GER, WVS.GER, EVS.CHI, WVS.CHI, EVS.COL, WVS.COL, EVS.CRO, WVS.CRO, EVS.ESA, WVS.ESA,
   EVS.EST, WVS.EST, EVS.FIN, WVS.FIN, EVS.FRA, WVS.FRA, EVS.GEO, WVS.GEO, EVS.HUN, WVS.HUN, EVS.IND, WVS.IND, EVS.INA, WVS.INA, EVS.IRI, WVS.IRI, EVS.IRQ,
   WVS.IRQ, EVS.ISR, WVS.ISR, EVS.ITA, WVS.ITA, EVS.JPN, WVS.JPN, EVS.KSA, WVS.KSA, EVS.JOR, WVS.JOR, EVS.KGZ, WVS.KGZ, EVS.LAT, WVS.LAT, EVS.LTU, WVS.LTU,
   EVS.MEX, WVS.MEX, EVS.MKD, WVS.MKD, EVS.MDA, WVS.MDA, EVS.MAR, WVS.MAR, EVS.NED, WVS.NED, EVS.NZL, WVS.NZL, EVS.NGR, WVS.NGR, EVS.NOR, WVS.NOR, EVS.PAK,
   WVS.PAK, EVS.PER, WVS.PER, EVS.PHI, WVS.PHI, EVS.POL, WVS.POL, EVS.PUR, WVS.PUR, EVS.ROU, WVS.ROU, EVS.RUS, WVS.RUS, EVS.SGP, WVS.SGP, EVS.SVK, WVS.SVK,
   EVS.SLO, WVS.SLO, EVS.RSA, WVS.RSA, EVS.ZIM, WVS.ZIM, EVS.ESP, WVS.ESP, EVS.SWE, WVS.SWE, EVS.SUI, WVS.SUI, EVS.TUR, WVS.TUR, EVS.UGA, WVS.UGA, EVS.UKR,
   WVS.UKR, EVS.EGY, WVS.EGY, EVS.TAN, WVS.TAN, EVS.USA, WVS.USA, EVS.URU, WVS.URU, EVS.CZE, WVS.CZE, EVS.GBR, WVS.GBR)

# Only in EVS
AUT <- EVSfinal %>% filter(IOC=="AUT") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
BEL <- EVSfinal %>% filter(IOC=="BEL") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
DEN <- EVSfinal %>% filter(IOC=="DEN") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
FRG <- EVSfinal %>% filter(IOC=="FRG") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
GRE <- EVSfinal %>% filter(IOC=="GRE") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
ISL <- EVSfinal %>% filter(IOC=="ISL") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
POR <- EVSfinal %>% filter(IOC=="POR") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
LUX <- EVSfinal %>% filter(IOC=="LUX") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
MLT <- EVSfinal %>% filter(IOC=="MLT") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
IRL <- EVSfinal %>% filter(IOC=="IRL") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
SRB <- EVSfinal %>% filter(IOC=="SRB") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 


# Only in WVS
AND <- WVSfinal %>% filter(IOC=="AND") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
ETH <- WVSfinal %>% filter(IOC=="ETH") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
GHA <- WVSfinal %>% filter(IOC=="GHA") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
GUA <- WVSfinal %>% filter(IOC=="GUA") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
HKG <- WVSfinal %>% filter(IOC=="HKG") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
RWA <- WVSfinal %>% filter(IOC=="RWA") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
THA <- WVSfinal %>% filter(IOC=="THA") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
TTO <- WVSfinal %>% filter(IOC=="TTO") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
ZAM <- WVSfinal %>% filter(IOC=="ZAM") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
HAI <- WVSfinal %>% filter(IOC=="HAI") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
LIB <- WVSfinal %>% filter(IOC=="LIB") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
LBA <- WVSfinal %>% filter(IOC=="LBA") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
QAT <- WVSfinal %>% filter(IOC=="QAT") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
TUN <- WVSfinal %>% filter(IOC=="TUN") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
UZB <- WVSfinal %>% filter(IOC=="UZB") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
YEM <- WVSfinal %>% filter(IOC=="YEM") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
MAS <- WVSfinal %>% filter(IOC=="MAS") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
MLI <- WVSfinal %>% filter(IOC=="MLI") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
KAZ <- WVSfinal %>% filter(IOC=="KAZ") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
KUW <- WVSfinal %>% filter(IOC=="KUW") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
BUR <- WVSfinal %>% filter(IOC=="BUR") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 
BIH <- WVSfinal %>% filter(IOC=="BIH") %>% filter(syear < 2010) %>% na.omit() %>% mutate(prop= sum(thrift==1)/length(as.factor(respondent))) %>% mutate(prop2= sum(trust==1)/length(as.factor(respondent))) 


WVSEVSthrifttrust <- rbind(ALB, ALG, AND, ARG, ARM, AUS, AUT, AZE, BAN, BEL, BLR, BRA, BUL, BUR, CAN, CHI, COL, CRO, DEN, EGY, ESA, ESP, EST, ETH, FIN, FRA, FRG,
                      GEO, GER, GHA, GRE, GUA, HAI, HKG, HUN, INA, IND, IRI, IRL, IRQ, ISL, ISR, ITA, JOR, JPN, KAZ, KGZ, KSA, KUW, LAT, LBA, LIB, LTU,
                      LUX, MAR, MAS, MDA, MEX, MKD, MLI, MLT, NED, NGR, NOR, NZL, PAK, PER, PHI, POL, POR, PUR, QAT, ROU, RSA, RUS, RWA, SGP, SLO, SUI,
                      SVK, SWE, TAN, THA, TTO, TUN, TUR, UGA, UKR, URU, USA, UZB, VEN, YEM, ZAM, ZIM, GBR, CZE, SRB, BIH)

WVSEVSthrifttrust <- WVSEVSthrifttrust %>% mutate(thrift_prop= prop*100) %>% mutate(trust_prop= prop2*100)

rm(ALB, ALG, AND, ARG, ARM, AUS, AUT, AZE, BAN, BEL, BLR, BRA, BUL, BUR, CAN, CHI, COL, CRO, DEN, EGY, ESA, ESP, EST, ETH, FIN, FRA, FRG,
   GEO, GER, GHA, GRE, GUA, HAI, HKG, HUN, INA, IND, IRI, IRL, IRQ, ISL, ISR, ITA, JOR, JPN, KAZ, KGZ, KSA, KUW, LAT, LBA, LIB, LTU,
   LUX, MAR, MAS, MDA, MEX, MKD, MLI, MLT, NED, NGR, NOR, NZL, PAK, PER, PHI, POL, POR, PUR, QAT, ROU, RSA, RUS, RWA, SGP, SLO, SUI,
   SVK, SWE, TAN, THA, TTO, TUN, TUR, UGA, UKR, URU, USA, UZB, VEN, YEM, ZAM, ZIM, GBR, CZE, SRB, BIH)


### Data Frame: thrift (WVS) ###
WVSthrift <- WVSEVSthrifttrust %>% select(IOC, prop, thrift_prop) %>% distinct()

thrift <- left_join(finalsample, WVSthrift)
